import Link from "next/link";
import type { Metadata } from "next";
import { getAllArticles } from "@/lib/articles";
import {
  getArticleCounts,
  getSourceCounts,
  TRACK_SOURCES,
  type EventCounts,
  type TrackSource,
} from "@/lib/analytics";

// First-party funnel dashboard. Localhost only (proxy.ts 404s /admin in
// prod), so it reads the PROD analytics namespace by default to show real
// visitor data. `?ns=dev` switches to the dev namespace for inspecting
// events generated by local browsing / testing.

export const metadata: Metadata = {
  title: "Analytics, admin",
  description: "Per-article email funnel + scroll drop-off.",
};

export const dynamic = "force-dynamic";

function n(counts: EventCounts, key: keyof EventCounts): number {
  return counts[key] ?? 0;
}

function pct(part: number, whole: number): string {
  if (whole <= 0) return "—";
  return `${Math.round((part / whole) * 1000) / 10}%`;
}

type Row = {
  slug: string;
  title: string;
  c: EventCounts;
};

export default async function AnalyticsAdminPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const dev = params.ns === "dev";

  const articles = getAllArticles();
  const slugs = articles.map((a) => a.slug);
  const [counts, sources] = await Promise.all([
    getArticleCounts(slugs, dev),
    getSourceCounts(dev),
  ]);

  const rows: Row[] = articles
    .map((a) => ({ slug: a.slug, title: a.title, c: counts.get(a.slug) ?? {} }))
    .sort((a, b) => n(b.c, "view") - n(a.c, "view"));

  // Site-wide totals (summed from the per-article counters, so no extra
  // global keys to maintain).
  const totals: EventCounts = {};
  for (const r of rows) {
    for (const key of Object.keys(r.c) as (keyof EventCounts)[]) {
      totals[key] = (totals[key] ?? 0) + (r.c[key] ?? 0);
    }
  }

  const totalViews = n(totals, "view");
  const totalSuccess = n(totals, "sub_success");

  return (
    <div className="max-w-6xl mx-auto px-6 pt-12 md:pt-16 pb-24">
      <header className="mb-8">
        <p className="eyebrow mb-2">Admin · Funnel</p>
        <h1
          className="font-display text-ink tracking-tight"
          style={{ fontSize: "clamp(1.8rem, 4vw, 2.6rem)", fontWeight: 700 }}
        >
          Reader analytics
        </h1>
        <p className="font-serif text-ink-muted mt-3 leading-relaxed">
          First-party, cookieless. Reading{" "}
          <strong className="text-ink">
            {dev ? "dev (local)" : "production"}
          </strong>{" "}
          data.{" "}
          <Link
            href={dev ? "/admin/analytics" : "/admin/analytics?ns=dev"}
            className="text-eye-deep hover:text-ink underline"
          >
            {dev ? "View production" : "View dev"}
          </Link>
        </p>
      </header>

      {/* Headline numbers */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-10">
        <Stat label="Article views" value={totalViews} />
        <Stat label="Reached form" value={n(totals, "form_seen")} />
        <Stat label="Submitted" value={n(totals, "sub_submit")} />
        <Stat
          label="Confirmed"
          value={totalSuccess}
          sub={pct(totalSuccess, totalViews) + " of views"}
        />
      </div>

      {/* Per-article funnel + scroll drop-off */}
      <h2 className="eyebrow mb-3">By article</h2>
      <div className="overflow-x-auto border border-rule">
        <table className="w-full text-sm" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr className="text-left text-ink-faint uppercase tracking-wider">
              <Th className="text-left">Article</Th>
              <Th>Views</Th>
              <Th>25%</Th>
              <Th>50%</Th>
              <Th>75%</Th>
              <Th>100%</Th>
              <Th>Form seen</Th>
              <Th>Sub</Th>
              <Th>Conf.</Th>
              <Th>Conv.</Th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => {
              const v = n(r.c, "view");
              return (
                <tr key={r.slug} className="border-t border-rule">
                  <Td className="text-left">
                    <Link
                      href={`/${r.slug}`}
                      className="text-ink hover:text-eye-deep font-medium"
                    >
                      {r.title}
                    </Link>
                  </Td>
                  <Td>{v.toLocaleString()}</Td>
                  <Td sub={pct(n(r.c, "scroll_25"), v)}>
                    {n(r.c, "scroll_25").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_50"), v)}>
                    {n(r.c, "scroll_50").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_75"), v)}>
                    {n(r.c, "scroll_75").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_100"), v)}>
                    {n(r.c, "scroll_100").toLocaleString()}
                  </Td>
                  <Td>{n(r.c, "form_seen").toLocaleString()}</Td>
                  <Td>{n(r.c, "sub_submit").toLocaleString()}</Td>
                  <Td>{n(r.c, "sub_success").toLocaleString()}</Td>
                  <Td>{pct(n(r.c, "sub_success"), v)}</Td>
                </tr>
              );
            })}
            {rows.every((r) => n(r.c, "view") === 0) && (
              <tr className="border-t border-rule">
                <Td className="text-left text-ink-faint" colSpan={10}>
                  No events recorded yet
                  {dev ? "" : " (data starts after the next deploy gets traffic)"}.
                </Td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Conversion attribution by surface — free email signups AND the
          paid funnel (checkout started -> became member), so you can see
          which surface actually earns paying members, not just clicks. */}
      <h2 className="eyebrow mt-12 mb-3">Conversions by source</h2>
      <div className="overflow-x-auto border border-rule max-w-xl">
        <table className="w-full text-sm" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr className="text-left text-ink-faint uppercase tracking-wider">
              <Th className="text-left">Source</Th>
              <Th>Email sub</Th>
              <Th>Email conf.</Th>
              <Th>Checkout</Th>
              <Th>Member</Th>
            </tr>
          </thead>
          <tbody>
            {TRACK_SOURCES.map((s: TrackSource) => {
              const c = sources.get(s) ?? {};
              return (
                <tr key={s} className="border-t border-rule">
                  <Td className="text-left">{s}</Td>
                  <Td>{n(c, "sub_submit").toLocaleString()}</Td>
                  <Td>{n(c, "sub_success").toLocaleString()}</Td>
                  <Td>{n(c, "checkout_started").toLocaleString()}</Td>
                  <Td>{n(c, "became_member").toLocaleString()}</Td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <p className="font-serif italic text-ink-faint text-sm mt-8 leading-relaxed max-w-xl">
        Funnel reads left to right: a view, how far they scrolled, whether
        they reached the inline form, and whether they subscribed. The
        scroll percentages show drop-off through the body.
      </p>
    </div>
  );
}

function Stat({
  label,
  value,
  sub,
}: {
  label: string;
  value: number;
  sub?: string;
}) {
  return (
    <div className="border border-rule p-4">
      <p className="eyebrow text-ink-faint mb-1">{label}</p>
      <p
        className="font-display text-ink"
        style={{ fontSize: "1.8rem", fontWeight: 700 }}
      >
        {value.toLocaleString()}
      </p>
      {sub && <p className="text-xs text-ink-faint mt-1">{sub}</p>}
    </div>
  );
}

function Th({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <th
      className={`px-3 py-2 text-right font-medium text-[0.68rem] ${className}`}
    >
      {children}
    </th>
  );
}

function Td({
  children,
  sub,
  className = "",
  colSpan,
}: {
  children: React.ReactNode;
  sub?: string;
  className?: string;
  colSpan?: number;
}) {
  return (
    <td className={`px-3 py-2 text-right tabular-nums ${className}`} colSpan={colSpan}>
      <span className="text-ink">{children}</span>
      {sub && sub !== "—" && (
        <span className="block text-[0.65rem] text-ink-faint">{sub}</span>
      )}
    </td>
  );
}
