import Link from "next/link";
import type { Metadata } from "next";
import { getAllArticles, getEarlyAccessArticle } from "@/lib/articles";
import {
  getArticleCounts,
  getChannelCounts,
  getSourceCounts,
  TRACK_CHANNELS,
  TRACK_SOURCES,
  type EventCounts,
  type TrackChannel,
  type TrackSource,
} from "@/lib/analytics";
import { getEngagementStats, getMembershipStats } from "@/lib/member-stats";

// First-party funnel dashboard. Localhost only (proxy.ts 404s /admin in
// prod), so it reads the PROD analytics namespace by default to show real
// visitor data. `?ns=dev` switches to the dev namespace for inspecting
// events generated by local browsing / testing.

export const metadata: Metadata = {
  title: "Analytics, admin",
  description: "Per-article email funnel + scroll drop-off.",
};

export const dynamic = "force-dynamic";

function n(counts: EventCounts, key: keyof EventCounts): number {
  return counts[key] ?? 0;
}

function pct(part: number, whole: number): string {
  if (whole <= 0) return "—";
  return `${Math.round((part / whole) * 1000) / 10}%`;
}

function money(cents: number): string {
  return `$${(cents / 100).toLocaleString(undefined, {
    maximumFractionDigits: 0,
  })}`;
}

type Row = {
  slug: string;
  title: string;
  c: EventCounts;
};

// Non-article pages instrumented with the same view/scroll/form_seen/sub
// funnel (ReadingTracker + TrackOnView). They write to analytics:article:<slug>
// like an article but aren't in getAllArticles(), so they get their own table.
const STATIC_FUNNEL: { slug: string; title: string }[] = [
  { slug: "about", title: "About" },
];

export default async function AnalyticsAdminPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const dev = params.ns === "dev";

  const articles = getAllArticles();
  // The draft is deliberately absent from getAllArticles, but it is the
  // ONLY piece that can accrue gate_shown — the gate exists exactly while
  // a piece is unpublished. Fetch its counters explicitly or the members-
  // first window would be recorded and never displayed.
  const draft = getEarlyAccessArticle();
  const slugs = [
    ...articles.map((a) => a.slug),
    ...(draft ? [draft.slug] : []),
  ];
  const [counts, staticCounts, sources, channels, membership, engagement] =
    await Promise.all([
      getArticleCounts(slugs, dev),
      getArticleCounts(
        STATIC_FUNNEL.map((p) => p.slug),
        dev
      ),
      getSourceCounts(dev),
      getChannelCounts(dev),
      getMembershipStats(dev),
      getEngagementStats(),
    ]);

  const staticRows: Row[] = STATIC_FUNNEL.map((p) => ({
    slug: p.slug,
    title: p.title,
    c: staticCounts.get(p.slug) ?? {},
  }));

  const rows: Row[] = articles
    .map((a) => ({ slug: a.slug, title: a.title, c: counts.get(a.slug) ?? {} }))
    .sort((a, b) => n(b.c, "view") - n(a.c, "view"));

  // Site-wide totals (summed from the per-article counters, so no extra
  // global keys to maintain).
  const totals: EventCounts = {};
  for (const r of rows) {
    for (const key of Object.keys(r.c) as (keyof EventCounts)[]) {
      totals[key] = (totals[key] ?? 0) + (r.c[key] ?? 0);
    }
  }

  const totalViews = n(totals, "view");
  const totalSuccess = n(totals, "sub_success");

  // Sign-in events carry no slug, so they live in the "signin" source
  // bucket rather than in any per-article counter.
  const signin = sources.get("signin") ?? {};

  return (
    <div className="max-w-6xl mx-auto px-6 pt-12 md:pt-16 pb-24">
      <header className="mb-8">
        <p className="eyebrow mb-2">Admin · Funnel</p>
        <h1
          className="font-display text-ink tracking-tight"
          style={{ fontSize: "clamp(1.8rem, 4vw, 2.6rem)", fontWeight: 700 }}
        >
          Reader analytics
        </h1>
        <p className="font-serif text-ink-muted mt-3 leading-relaxed">
          First-party, cookieless. Reading{" "}
          <strong className="text-ink">
            {dev ? "dev (local)" : "production"}
          </strong>{" "}
          data.{" "}
          <Link
            href={dev ? "/admin/analytics" : "/admin/analytics?ns=dev"}
            className="text-eye-deep hover:text-ink underline"
          >
            {dev ? "View production" : "View dev"}
          </Link>
        </p>
      </header>

      {/* Membership — GROUND TRUTH from members:all, not event counters.
          The funnel events below only count members who joined after the
          tracking shipped; this is the real roster. */}
      <h2 className="eyebrow mb-3">Membership (actual)</h2>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
        <Stat label="Members" value={membership.total} />
        <Stat label="Active now" value={membership.active} />
        <Stat label="Joined (30d)" value={membership.joined30d} sub={`${membership.joined7d} in 7d`} />
        <Stat label="Est. MRR" valueText={money(membership.mrrCents)} sub="active, monthly-equiv" />
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-10">
        <Stat
          label="Tier mix (active)"
          valueText={`${membership.tiers.founder}f · ${membership.tiers.charter}c · ${membership.tiers.regular}r`}
        />
        <Stat
          label="Billing (active)"
          valueText={`${membership.intervals.month} mo · ${membership.intervals.year} yr`}
        />
        <Stat
          label="Canceled (30d)"
          value={membership.canceled30d}
          sub={`${membership.canceled} all-time`}
        />
        <Stat
          label="30d churn"
          valueText={pct(
            membership.canceled30d,
            membership.active + membership.canceled30d
          )}
          sub="canceled / (active+canceled)"
        />
      </div>

      {/* Engagement — are members actually using the room? */}
      <h2 className="eyebrow mb-3">Engagement (last 30d)</h2>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-10">
        <Stat
          label="Active members"
          value={engagement.activeMembers30d}
          sub={pct(engagement.activeMembers30d, membership.active) + " of active"}
        />
        <Stat
          label="Comments"
          value={engagement.comments.d30}
          sub={`${engagement.comments.d7} in 7d`}
        />
        <Stat
          label="Lounge posts"
          value={engagement.lounge.d30}
          sub={`${engagement.lounge.d7} in 7d`}
        />
        <Stat
          label="Desk notes"
          value={engagement.notes.d30}
          sub={`${engagement.notes.d7} in 7d`}
        />
      </div>

      {/* Headline numbers */}
      <h2 className="eyebrow mb-3">Reader funnel</h2>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-10">
        <Stat label="Article views" value={totalViews} />
        <Stat label="Reached form" value={n(totals, "form_seen")} />
        <Stat label="Submitted" value={n(totals, "sub_submit")} />
        <Stat
          label="Confirmed"
          value={totalSuccess}
          sub={pct(totalSuccess, totalViews) + " of views"}
        />
      </div>

      {/* Per-article funnel + scroll drop-off */}
      <h2 className="eyebrow mb-3">By article</h2>
      <div className="overflow-x-auto border border-rule">
        <table className="w-full text-sm" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr className="text-left text-ink-faint uppercase tracking-wider">
              <Th className="text-left">Article</Th>
              <Th>Views</Th>
              <Th>25%</Th>
              <Th>50%</Th>
              <Th>75%</Th>
              <Th>100%</Th>
              <Th>Form seen</Th>
              <Th>Sub</Th>
              <Th>Conf.</Th>
              <Th>Conv.</Th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => {
              const v = n(r.c, "view");
              return (
                <tr key={r.slug} className="border-t border-rule">
                  <Td className="text-left">
                    <Link
                      href={`/${r.slug}`}
                      className="text-ink hover:text-eye-deep font-medium"
                    >
                      {r.title}
                    </Link>
                  </Td>
                  <Td>{v.toLocaleString()}</Td>
                  <Td sub={pct(n(r.c, "scroll_25"), v)}>
                    {n(r.c, "scroll_25").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_50"), v)}>
                    {n(r.c, "scroll_50").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_75"), v)}>
                    {n(r.c, "scroll_75").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_100"), v)}>
                    {n(r.c, "scroll_100").toLocaleString()}
                  </Td>
                  <Td>{n(r.c, "form_seen").toLocaleString()}</Td>
                  <Td>{n(r.c, "sub_submit").toLocaleString()}</Td>
                  <Td>{n(r.c, "sub_success").toLocaleString()}</Td>
                  <Td>{pct(n(r.c, "sub_success"), v)}</Td>
                </tr>
              );
            })}
            {rows.every((r) => n(r.c, "view") === 0) && (
              <tr className="border-t border-rule">
                <Td className="text-left text-ink-faint" colSpan={10}>
                  No events recorded yet
                  {dev ? "" : " (data starts after the next deploy gets traffic)"}.
                </Td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Static pages — non-article surfaces instrumented with the same
          funnel (e.g. /about). Same columns as the article table so the
          landed -> form -> signup drop-off reads the same way. */}
      <h2 className="eyebrow mt-12 mb-3">Static pages</h2>
      <div className="overflow-x-auto border border-rule">
        <table className="w-full text-sm" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr className="text-left text-ink-faint uppercase tracking-wider">
              <Th className="text-left">Page</Th>
              <Th>Views</Th>
              <Th>25%</Th>
              <Th>50%</Th>
              <Th>75%</Th>
              <Th>100%</Th>
              <Th>Form seen</Th>
              <Th>Sub</Th>
              <Th>Conf.</Th>
              <Th>Conv.</Th>
            </tr>
          </thead>
          <tbody>
            {staticRows.map((r) => {
              const v = n(r.c, "view");
              return (
                <tr key={r.slug} className="border-t border-rule">
                  <Td className="text-left">
                    <Link
                      href={`/${r.slug}`}
                      className="text-ink hover:text-eye-deep font-medium"
                    >
                      {r.title}
                    </Link>
                  </Td>
                  <Td>{v.toLocaleString()}</Td>
                  <Td sub={pct(n(r.c, "scroll_25"), v)}>
                    {n(r.c, "scroll_25").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_50"), v)}>
                    {n(r.c, "scroll_50").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_75"), v)}>
                    {n(r.c, "scroll_75").toLocaleString()}
                  </Td>
                  <Td sub={pct(n(r.c, "scroll_100"), v)}>
                    {n(r.c, "scroll_100").toLocaleString()}
                  </Td>
                  <Td>{n(r.c, "form_seen").toLocaleString()}</Td>
                  <Td>{n(r.c, "sub_submit").toLocaleString()}</Td>
                  <Td>{n(r.c, "sub_success").toLocaleString()}</Td>
                  <Td>{pct(n(r.c, "sub_success"), v)}</Td>
                </tr>
              );
            })}
            {staticRows.every((r) => n(r.c, "view") === 0) && (
              <tr className="border-t border-rule">
                <Td className="text-left text-ink-faint" colSpan={10}>
                  No events recorded yet
                  {dev ? "" : " (data starts after the next deploy gets traffic)"}.
                </Td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Gift funnel — pay-it-forward seats. Purchased on the Stripe
          webhook, redeemed when the recipient claims, converted when a
          gifted recipient later subscribes on their own card. All three
          roll up under the "gift" source counter. */}
      <h2 className="eyebrow mt-12 mb-3">Gift funnel</h2>
      <div className="grid grid-cols-3 gap-4 max-w-xl">
        <Stat
          label="Purchased"
          value={n(sources.get("gift") ?? {}, "gift_purchased")}
        />
        <Stat
          label="Redeemed"
          value={n(sources.get("gift") ?? {}, "gift_redeemed")}
          sub={
            pct(
              n(sources.get("gift") ?? {}, "gift_redeemed"),
              n(sources.get("gift") ?? {}, "gift_purchased")
            ) + " of purchased"
          }
        />
        <Stat
          label="Converted"
          value={n(sources.get("gift") ?? {}, "gift_converted")}
          sub={
            pct(
              n(sources.get("gift") ?? {}, "gift_converted"),
              n(sources.get("gift") ?? {}, "gift_redeemed")
            ) + " of redeemed"
          }
        />
      </div>

      {/* Conversion attribution by surface — free email signups AND the
          paid funnel (checkout started -> became member), so you can see
          which surface actually earns paying members, not just clicks. */}
      <h2 className="eyebrow mt-12 mb-3">Conversions by source</h2>
      <div className="overflow-x-auto border border-rule max-w-xl">
        <table className="w-full text-sm" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr className="text-left text-ink-faint uppercase tracking-wider">
              <Th className="text-left">Source</Th>
              <Th>Email sub</Th>
              <Th>Email conf.</Th>
              <Th>Checkout</Th>
              <Th>Member</Th>
            </tr>
          </thead>
          <tbody>
            {TRACK_SOURCES.map((s: TrackSource) => {
              const c = sources.get(s) ?? {};
              return (
                <tr key={s} className="border-t border-rule">
                  <Td className="text-left">{s}</Td>
                  <Td>{n(c, "sub_submit").toLocaleString()}</Td>
                  <Td>{n(c, "sub_success").toLocaleString()}</Td>
                  <Td>{n(c, "checkout_started").toLocaleString()}</Td>
                  <Td>{n(c, "became_member").toLocaleString()}</Td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Acquisition by channel — first-touch (where the visitor came
          from off-site), so you can see which channel drives views AND
          which actually earns paying members. Empty until first-touch
          traffic accrues after deploy. */}
      <h2 className="eyebrow mt-12 mb-3">Acquisition by channel</h2>
      <div className="overflow-x-auto border border-rule max-w-xl">
        <table className="w-full text-sm" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr className="text-left text-ink-faint uppercase tracking-wider">
              <Th className="text-left">Channel</Th>
              <Th>Visits</Th>
              <Th>Checkout</Th>
              <Th>Member</Th>
              <Th>Conv.</Th>
            </tr>
          </thead>
          <tbody>
            {TRACK_CHANNELS.map((ch: TrackChannel) => {
              const c = channels.get(ch) ?? {};
              const v = n(c, "view");
              return (
                <tr key={ch} className="border-t border-rule">
                  <Td className="text-left">{ch}</Td>
                  <Td>{v.toLocaleString()}</Td>
                  <Td>{n(c, "checkout_started").toLocaleString()}</Td>
                  <Td>{n(c, "became_member").toLocaleString()}</Td>
                  <Td>{pct(n(c, "became_member"), v)}</Td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* The way in. Two surfaces that were previously invisible and that
          only a reader emailing to complain ever surfaced: the draft gate
          (strangers hitting a members-only piece) and the sign-in no-match
          (people who tried to get in under an address with no membership
          behind it). The gate half is unrepeatable — it can only be
          measured while a piece is unpublished. */}
      <h2 className="eyebrow mt-12 mb-3">The way in</h2>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 max-w-3xl">
        <Stat
          label={draft ? "Gate shown" : "Gate shown (no draft)"}
          value={draft ? n(counts.get(draft.slug) ?? {}, "gate_shown") : 0}
          sub={draft ? draft.title : "nothing unpublished right now"}
        />
        <Stat
          label="Sign-in requests"
          value={n(signin, "signin_requested")}
          sub="past rate limit, excludes admin"
        />
        <Stat
          label="No membership found"
          value={n(signin, "signin_no_match")}
          sub="each one gets the note"
        />
        <Stat
          label="Matched"
          valueText={pct(
            n(signin, "signin_requested") - n(signin, "signin_no_match"),
            n(signin, "signin_requested")
          )}
          sub="requests that got a real link"
        />
      </div>

      <p className="font-serif italic text-ink-faint text-sm mt-8 leading-relaxed max-w-xl">
        Funnel reads left to right: a view, how far they scrolled, whether
        they reached the inline form, and whether they subscribed. The
        scroll percentages show drop-off through the body.
      </p>
    </div>
  );
}

function Stat({
  label,
  value,
  valueText,
  sub,
}: {
  label: string;
  value?: number;
  /** Use for non-numeric values (money, mixes). Takes precedence. */
  valueText?: string;
  sub?: string;
}) {
  return (
    <div className="border border-rule p-4">
      <p className="eyebrow text-ink-faint mb-1">{label}</p>
      <p
        className="font-display text-ink"
        style={{ fontSize: "1.8rem", fontWeight: 700 }}
      >
        {valueText ?? (value ?? 0).toLocaleString()}
      </p>
      {sub && <p className="text-xs text-ink-faint mt-1">{sub}</p>}
    </div>
  );
}

function Th({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <th
      className={`px-3 py-2 text-right font-medium text-[0.68rem] ${className}`}
    >
      {children}
    </th>
  );
}

function Td({
  children,
  sub,
  className = "",
  colSpan,
}: {
  children: React.ReactNode;
  sub?: string;
  className?: string;
  colSpan?: number;
}) {
  return (
    <td className={`px-3 py-2 text-right tabular-nums ${className}`} colSpan={colSpan}>
      <span className="text-ink">{children}</span>
      {sub && sub !== "—" && (
        <span className="block text-[0.65rem] text-ink-faint">{sub}</span>
      )}
    </td>
  );
}
